//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BatchNamer.rc에서 사용되고 있습니다.
//
#define IDS_TB_00                       1
#define IDS_TB_01                       2
#define IDS_TB_02                       3
#define IDS_TB_03                       4
#define IDS_TB_04                       5
#define IDS_TB_05                       6
#define IDS_TB_06                       7
#define IDS_TB_07                       8
#define IDS_TB_08                       9
#define IDS_TB_09                       10
#define IDS_TB_10                       11
#define IDS_TB_11                       12
#define IDS_TB_12                       13
#define IDS_TB_13                       14
#define IDS_TB_14                       15
#define IDS_TB_15                       16
#define IDS_TB_16                       17
#define IDS_TB_17                       18
#define IDS_TB_18                       19
#define IDS_TB_19                       20
#define IDS_ADDSTRING                   21
#define IDS_ADDPARENT                   22
#define IDS_STRINGTOADD                 23
#define IDS_WORKING                     24
#define IDS_COL_OLDNAME                 25
#define IDS_COL_NEWNAME                 26
#define IDS_COL_FULLPATH                27
#define IDS_COL_OLDFOLDER               28
#define IDS_COL_NEWFOLDER               29
#define IDS_COL_FILESIZE                30
#define IDS_COL_TIMECREATE              31
#define IDS_COL_TIMEMODIFY              32
#define IDS_ERR_TOOMANYITEMS            33
#define IDS_LOAD_FILEDIALOG             34
#define IDS_PLEASE_ADD                  35
#define IDS_COUNT_FORMAT                36
#define IDS_IMPORT_PATH                 37
#define IDS_CONFIRM_EXIT                38
#define IDS_POS_1                       39
#define IDS_POS_2                       40
#define IDS_DELPOS_FRONT                41
#define IDS_DELPOS_REAR                 42
#define IDS_MSG_INVALIDPOS              43
#define IDS_MANUAL_CHANGE               44
#define IDS_POS_1_REAR                  45
#define IDS_ADDPREFIX                   46
#define IDS_ADDSUFFIX                   47
#define IDS_REMOVEBYBRACKET             48
#define IDS_MSG_BRACKETINVALID          49
#define IDS_MSG_APPLYASK                50
#define IDS_MSG_NONAME                  51
#define IDS_MSG_DUPNAME                 52
#define IDS_MSG_MISMATCH                53
#define IDS_MSG_CHANGEFAIL              54
#define IDS_MSG_CHANGEDONE              55
#define IDS_MSG_INVALIDFONTSIZE         56
#define IDS_ICON_LARGE                  57
#define IDS_ICON_SMALL                  58
#define IDS_ICON_EXLARGE                59
#define IDS_ICON_JUMBO                  60
#define IDS_REPLACESTRING               61
#define IDS_REPLACEOLD                  62
#define IDS_REPLACENEW                  63
#define IDS_ADDTIMECREATE               64
#define IDS_ADDTIMEMODIFY               65
#define IDS_BRACKET1                    66
#define IDS_BRACKET2                    67
#define IDS_MSG_BRACKETLEN              68
#define IDS_SETPARENT                   69
#define IDS_IMPORTNAME                  70
#define IDS_EXPORTNAME                  71
#define IDS_EXPORTFULLPATH              72
#define IDS_DIGITBACK                   73
#define IDS_DIGITFRONT                  74
#define IDS_DIGITCOUNT                  75
#define IDS_MSG_INVALIDDIGIT            76
#define IDS_EXT_APPEND                  77
#define IDS_EXT_TOADD                   78
#define IDS_EXT_REPLACE                 79
#define IDS_EXT_OLD                     80
#define IDS_EXT_NEW                     81
#define IDS_STARTNUMBER                 82
#define IDS_ADDNUM_ALL_BACK             83
#define IDS_ADDNUM_ALL_FRONT            84
#define IDS_ADDNUM_BYFOLDER_BACK        85
#define IDS_ADDNUM_BYFOLDER_FRONT       86
#define IDS_ADDNUM_BYFOLDER_FRONT2      87
#define IDS_MSG_STOPTHREAD              87
#define IDS_PROGRESS_CHANGE             88
#define IDS_ADDDATECREATE               89
#define IDS_ADDDATEMODIFY               90
#define IDS_PRESET_NAME_FORMAT          91
#define IDS_PRESET_NAME                 92
#define IDS_PRESET_NAME_DESC            93
#define IDS_PRESET_MENU_FORMAT          94
#define IDS_PRESET_NONAME               95
#define IDS_PRESET_COMMAND              96
#define IDS_PRESET_SUBCOMMAND           97
#define IDS_PRESET_ARG1                 98
#define IDS_PRESET_ARG2                 99
#define IDS_INVALID_CHAR                100
#define IDS_MSG_ERROR                   101
#define IDD_BATCHNAMER                  102
#define IDS_MSG_VERSION                 102
#define IDS_MSG_SAMENAME                103
#define IDS_RESULT_REPORT               104
#define IDS_ASK_FOLDERLOADING           105
#define IDS_FLIPSTRING                  106
#define IDS_FLIPPIVOT                   107
#define IDS_INVALID_WILDCARD            108
#define IDS_INVALID_WILDCARD_PAIR       109
#define IDS_LOWERCASE                   110
#define IDS_UPPERCASE                   111
#define IDS_UPPERCASE_FIRST             112
#define IDS_UPPERCASE_WORD              113
#define IDS_INSERT_BYPOS_FRONT          114
#define IDS_INSERT_BYPOS_BACK           115
#define IDS_ADDDATETIMECREATE           116
#define IDS_ADDDATETIMEMODIFY           117
#define IDR_MAINFRAME                   128
#define IDD_INPUT                       129
#define IDR_TOOLBAR1                    130
#define IDR_TOOLBAR2                    132
#define IDR_MENU_MAIN                   134
#define IDD_CFG_LOAD                    137
#define IDD_CFG_VIEW                    141
#define IDD_SORT                        149
#define IDD_PRESET                      151
#define IDR_TOOLBAR_PRESET              153
#define IDD_MSG                         155
#define IDD_CFG_ETC                     157
#define IDC_LIST_FILE                   1000
#define IDC_STATIC_TITLE                1001
#define IDC_LIST_PRESET                 1001
#define IDC_STATIC_1                    1002
#define IDC_STATIC_2                    1003
#define IDC_EDIT_1                      1004
#define IDC_EDIT_2                      1005
#define IDC_CB_INPUT                    1006
#define IDC_ST_BAR                      1007
#define IDC_TOOLBORDER_1                1012
#define IDC_TOOLBORDER_2                1013
#define IDC_RADIO_LOAD_0                1014
#define IDC_RADIO_LOAD_1                1015
#define IDC_RADIO_LOAD_2                1016
#define IDC_RADIO_AUTOSORT_0            1019
#define IDC_RADIO_AUTOSORT_1            1020
#define IDC_CHECK_DEFAULT_COLOR         1023
#define IDC_CHECK_DEFAULT_FONT          1024
#define IDC_COLOR_BK                    1026
#define IDC_COLOR_TEXT                  1027
#define IDC_EDIT_FONTSIZE               1030
#define IDC_CB_ICONSIZE                 1031
#define IDC_ST_FONTSIZE                 1032
#define IDC_ST_COLOR_TEXT               1033
#define IDC_ST_COLOR_BK                 1034
#define IDC_CHK_SHOWEVERYTIME           1035
#define IDC_BTN_STOPTHREAD              1037
#define IDC_RADIO_SORT_ASCEND           1047
#define IDC_RADIO_SORT_DESCEND          1048
#define IDC_CB_SORTCOL                  1049
#define IDC_CB_PRESET_SELECT            1051
#define IDC_BTN_PRESET_TASK_EDIT        1055
#define IDC_BTN_PRESET_TASK_DELETE      1056
#define IDC_BTN_PRESET_TASK_ADD         1057
#define IDC_BTN_PRESET_NAME             1058
#define IDC_BTN_PRESET_DOWN             1059
#define IDC_BTN_PRESET_UP2              1060
#define IDC_BTN_PRESET_UP               1060
#define IDC_ST_PRESET_ADD               1061
#define IDC_EDIT_MSG                    1062
#define IDC_CHK_NAMEAUTOFIX             1063
#define IDC_LIST_HOTKEY                 1064
#define IDM_APPLY_CHANGE                32771
#define IDM_NAME_REPLACE                32772
#define IDM_NAME_ADD_FRONT              32773
#define IDM_NAME_ADD_REAR               32774
#define IDM_NAME_EMPTY                  32775
#define IDM_NAME_REMOVESELECTED         32776
#define IDM_NAME_EXTRACTNUMBER          32777
#define IDM_NAME_REMOVENUMBER           32778
#define IDM_NAME_DIGIT                  32779
#define IDM_NAME_ADDNUM                 32780
#define IDM_UNDO_CHANGE                 32781
#define IDM_CLEAR_LIST                  32782
#define IDM_MANUAL_CHANGE               32783
#define IDM_SORT_LIST                   32784
#define IDM_NAME_SETPARENT              32787
#define IDM_EXT_DEL                     32788
#define IDM_EXT_ADD                     32789
#define IDM_EXT_REPLACE                 32790
#define IDM_LIST_ADD                    32791
#define IDM_EXPORT_CLIP                 32792
#define IDM_EXPORT_FILE                 32793
#define IDM_EXPORT_CLIP2                32794
#define IDM_EXPORT_FILE2                32795
#define IDM_IMPORT_FILE                 32796
#define IDM_IMPORT_FILE2                32797
#define IDM_EDIT_UP                     32798
#define IDM_EDIT_DOWN                   32799
#define IDM_SHOW_FULLPATH               32800
#define IDM_SHOW_SIZE                   32801
#define IDM_SHOW_MODIFYTIME             32802
#define IDM_SHOW_CREATETIME             32803
#define IDM_VERSION                     32804
#define IDM_CFG_LOAD                    32812
#define IDM_SHOW_OLDFODER               32815
#define IDM_SHOW_NEWFOLDER              32816
#define IDM_SHOW_OLDFOLDER              32817
#define IDM_CFG_VIEW                    32819
#define IDM_PRESET_EDIT                 32820
#define IDM_PRESET_APPLY1               32821
#define IDM_PRESET_APPLY2               32822
#define IDM_PRESET_APPLY3               32823
#define IDM_PRESET_APPLY4               32824
#define IDM_PRESET_APPLY5               32825
#define ID_Menu                         32838
#define IDM_UNDO_SELECTED               32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
