//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BatchNamer.rc에서 사용되고 있습니다.
//
#define IDS_TB_00                       1
#define IDS_TB_01                       2
#define IDS_TB_02                       3
#define IDS_TB_03                       4
#define IDS_TB_04                       5
#define IDS_TB_05                       6
#define IDS_TB_06                       7
#define IDS_TB_07                       8
#define IDS_TB_08                       9
#define IDS_TB_09                       10
#define IDS_TB_10                       11
#define IDS_TB_11                       12
#define IDS_TB_12                       13
#define IDS_TB_13                       14
#define IDS_TB_14                       15
#define IDS_TB_15                       16
#define IDS_TB_16                       17
#define IDS_TB_17                       18
#define IDS_TB_18                       19
#define IDS_TB_19                       20
#define IDS_ADDSTRING                   21
#define IDS_ADDPARENT                   22
#define IDS_STRINGTOADD                 23
#define IDS_WORKING                     24
#define IDS_COL_OLDNAME                 25
#define IDS_COL_NEWNAME                 26
#define IDS_COL_FULLPATH                27
#define IDS_COL_OLDFOLDER               28
#define IDS_COL_NEWFOLDER               29
#define IDS_COL_FILESIZE                30
#define IDS_COL_TIMECREATE              31
#define IDS_COL_TIMEMODIFY              32
#define IDS_MSG_APPLYASK                50
#define IDS_MSG_NONAME                  51
#define IDS_MSG_DUPNAME                 52
#define IDS_MSG_MISMATCH                53
#define IDS_MSG_CHANGEFAIL              54
#define IDS_MSG_CHANGEDONE              55
#define IDS_MSG_INVALIDFONTSIZE         56
#define IDS_ICON_LARGE                  57
#define IDS_ICON_SMALL                  58
#define IDS_ICON_EXLARGE                59
#define IDS_ICON_JUMBO                  60
#define IDS_REPLACESTRING               61
#define IDS_REPLACEOLD                  62
#define IDS_REPLACENEW                  63
#define IDS_ADDTIMECREATE               64
#define IDS_ADDTIMEMODIFY               65
#define IDD_BATCHNAMER                  102
#define IDR_MAINFRAME                   128
#define IDD_INPUT                       129
#define IDR_TOOLBAR1                    130
#define IDR_TOOLBAR2                    132
#define IDR_MENU_MAIN                   134
#define IDD_CFG_LOAD                    137
#define IDD_CFG_VIEW                    141
#define IDC_LIST_FILE                   1000
#define IDC_STATIC_TITLE                1001
#define IDC_STATIC_1                    1002
#define IDC_STATIC_2                    1003
#define IDC_EDIT_1                      1004
#define IDC_EDIT_2                      1005
#define IDC_CB_INPUT                    1006
#define IDC_ST_BAR                      1007
#define IDC_TOOLBORDER_1                1012
#define IDC_TOOLBORDER_2                1013
#define IDC_RADIO_LOAD_1                1014
#define IDC_RADIO_LOAD_2                1015
#define IDC_RADIO_LOAD_3                1017
#define IDC_RADIO_LOAD_4                1018
#define IDC_RADIO_SHOW_0                1019
#define IDC_RADIO_SHOW_1                1020
#define IDC_RADIO_LOAD_0                1021
#define IDC_CHECK_DEFAULT_COLOR         1023
#define IDC_CHECK_DEFAULT_FONT          1024
#define IDC_COLOR_BK                    1026
#define IDC_COLOR_TEXT                  1027
#define IDC_EDIT_FONTSIZE               1030
#define IDC_CB_ICONSIZE                 1031
#define IDC_ST_FONTSIZE                 1032
#define IDC_ST_COLOR_TEXT               1033
#define IDC_ST_COLOR_BK                 1034
#define IDM_APPLY_CHANGE                32771
#define IDM_NAME_REPLACE                32772
#define IDM_NAME_ADD_FRONT              32773
#define IDM_NAME_ADD_REAR               32774
#define IDM_NAME_EMPTY                  32775
#define IDM_NAME_DELPOS                 32776
#define IDM_NAME_DELTOKEN               32777
#define IDM_NAME_DEL_TYPE               32778
#define IDM_NAME_DIGIT                  32779
#define IDM_NAME_ADDNUM                 32780
#define IDM_UNDO_CHANGE                 32781
#define IDM_CLEAR_LIST                  32782
#define IDM_MANUAL_CHANGE               32783
#define IDM_SORT_LIST                   32784
#define IDM_NAME_SAMEPATH               32787
#define IDM_EXT_DEL                     32788
#define IDM_EXT_ADD                     32789
#define IDM_EXT_REPLACE                 32790
#define IDM_LIST_ADD                    32791
#define IDM_EXPORT_CLIP                 32792
#define IDM_EXPORT_FILE                 32793
#define IDM_EXPORT_CLIP2                32794
#define IDM_EXPORT_FILE2                32795
#define IDM_IMPORT_FILE                 32796
#define IDM_IMPORT_FILE2                32797
#define IDM_EDIT_UP                     32798
#define IDM_EDIT_DOWN                   32799
#define IDM_SHOW_FULLPATH               32800
#define IDM_SHOW_SIZE                   32801
#define IDM_SHOW_MODIFYTIME             32802
#define IDM_SHOW_CREATETIME             32803
#define IDM_VERSION                     32804
#define IDM_CFG_LOAD                    32812
#define IDM_SHOW_OLDFODER               32815
#define IDM_SHOW_NEWFOLDER              32816
#define IDM_SHOW_OLDFOLDER              32817
#define IDM_CFG_VIEW                    32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
